name: Unit Test
run-name: Action triggered by @${{ github.actor }}

on:
  push:
    branches:
      - '*'
  pull_request:
    paths:
      - 'app/**'
    
jobs:
    lint:
      runs-on: ubuntu-latest

      steps:
        - name: Get the repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install black flake8

        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            black: true
            flake8: true


    build:
      runs-on: ubuntu-latest
      needs: lint
      steps: 
        - name: Get the repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install dependencies
          run: |
            python3 -m venv venv
            source ./venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Cache the venv dir
          uses: actions/cache/save@v4
          id: py-dep-cache
          with:
            path: ./venv
            key: py-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}


    unit-tests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Get the repo
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Restore virtual environment from cache
          uses: actions/cache/restore@v4
          id: py-dep-cache
          with:
              key: py-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
              path: ./venv

        - name: Run the unit tests
          run: | 
            source ./venv/bin/activate
            python -m unittest discover -s ./app/ -p '*_test.py'